//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseMate.Web.CMwcf {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/CourseMatesWS.DAL.Objects")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GCMIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GCMId {
            get {
                return this.GCMIdField;
            }
            set {
                if ((object.ReferenceEquals(this.GCMIdField, value) != true)) {
                    this.GCMIdField = value;
                    this.RaisePropertyChanged("GCMId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SQLStatus", Namespace="http://schemas.datacontract.org/2004/07/CourseMatesWS.BLL")]
    public enum SQLStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Succeeded = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Failed = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UserExists = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EmailExists = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Course", Namespace="http://schemas.datacontract.org/2004/07/CourseMatesWS.DAL.Objects")]
    [System.SerializableAttribute()]
    public partial class Course : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CourseAdminIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CourseNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CourseMate.Web.CMwcf.FileItem[] FilesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CourseMate.Web.CMwcf.FourmItem[] FourmItemsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IconClassField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsAdminField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CourseMate.Web.CMwcf.User[] ParticipantsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CourseAdminID {
            get {
                return this.CourseAdminIDField;
            }
            set {
                if ((this.CourseAdminIDField.Equals(value) != true)) {
                    this.CourseAdminIDField = value;
                    this.RaisePropertyChanged("CourseAdminID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CourseName {
            get {
                return this.CourseNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CourseNameField, value) != true)) {
                    this.CourseNameField = value;
                    this.RaisePropertyChanged("CourseName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CourseMate.Web.CMwcf.FileItem[] Files {
            get {
                return this.FilesField;
            }
            set {
                if ((object.ReferenceEquals(this.FilesField, value) != true)) {
                    this.FilesField = value;
                    this.RaisePropertyChanged("Files");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CourseMate.Web.CMwcf.FourmItem[] FourmItems {
            get {
                return this.FourmItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.FourmItemsField, value) != true)) {
                    this.FourmItemsField = value;
                    this.RaisePropertyChanged("FourmItems");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IconClass {
            get {
                return this.IconClassField;
            }
            set {
                if ((object.ReferenceEquals(this.IconClassField, value) != true)) {
                    this.IconClassField = value;
                    this.RaisePropertyChanged("IconClass");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsAdmin {
            get {
                return this.IsAdminField;
            }
            set {
                if ((this.IsAdminField.Equals(value) != true)) {
                    this.IsAdminField = value;
                    this.RaisePropertyChanged("IsAdmin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CourseMate.Web.CMwcf.User[] Participants {
            get {
                return this.ParticipantsField;
            }
            set {
                if ((object.ReferenceEquals(this.ParticipantsField, value) != true)) {
                    this.ParticipantsField = value;
                    this.RaisePropertyChanged("Participants");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FileItem", Namespace="http://schemas.datacontract.org/2004/07/CourseMatesWS.DAL.Objects")]
    [System.SerializableAttribute()]
    public partial class FileItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsFolderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LastModifyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OwnerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OwnerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PerantIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CourseMate.Web.CMwcf.FileItem[] SubItemsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CourseMate.Web.CMwcf.FileType TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileName {
            get {
                return this.FileNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FileNameField, value) != true)) {
                    this.FileNameField = value;
                    this.RaisePropertyChanged("FileName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsFolder {
            get {
                return this.IsFolderField;
            }
            set {
                if ((this.IsFolderField.Equals(value) != true)) {
                    this.IsFolderField = value;
                    this.RaisePropertyChanged("IsFolder");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastModify {
            get {
                return this.LastModifyField;
            }
            set {
                if ((this.LastModifyField.Equals(value) != true)) {
                    this.LastModifyField = value;
                    this.RaisePropertyChanged("LastModify");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OwnerId {
            get {
                return this.OwnerIdField;
            }
            set {
                if ((this.OwnerIdField.Equals(value) != true)) {
                    this.OwnerIdField = value;
                    this.RaisePropertyChanged("OwnerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OwnerName {
            get {
                return this.OwnerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.OwnerNameField, value) != true)) {
                    this.OwnerNameField = value;
                    this.RaisePropertyChanged("OwnerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PerantID {
            get {
                return this.PerantIDField;
            }
            set {
                if ((this.PerantIDField.Equals(value) != true)) {
                    this.PerantIDField = value;
                    this.RaisePropertyChanged("PerantID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Rate {
            get {
                return this.RateField;
            }
            set {
                if ((this.RateField.Equals(value) != true)) {
                    this.RateField = value;
                    this.RaisePropertyChanged("Rate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CourseMate.Web.CMwcf.FileItem[] SubItems {
            get {
                return this.SubItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.SubItemsField, value) != true)) {
                    this.SubItemsField = value;
                    this.RaisePropertyChanged("SubItems");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CourseMate.Web.CMwcf.FileType Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FourmItem", Namespace="http://schemas.datacontract.org/2004/07/CourseMatesWS.DAL.Objects")]
    [System.SerializableAttribute()]
    public partial class FourmItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CourseMate.Web.CMwcf.User OwnerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PerentIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Content {
            get {
                return this.ContentField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentField, value) != true)) {
                    this.ContentField = value;
                    this.RaisePropertyChanged("Content");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CourseMate.Web.CMwcf.User Owner {
            get {
                return this.OwnerField;
            }
            set {
                if ((object.ReferenceEquals(this.OwnerField, value) != true)) {
                    this.OwnerField = value;
                    this.RaisePropertyChanged("Owner");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PerentId {
            get {
                return this.PerentIdField;
            }
            set {
                if ((this.PerentIdField.Equals(value) != true)) {
                    this.PerentIdField = value;
                    this.RaisePropertyChanged("PerentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Rate {
            get {
                return this.RateField;
            }
            set {
                if ((this.RateField.Equals(value) != true)) {
                    this.RateField = value;
                    this.RaisePropertyChanged("Rate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FileType", Namespace="http://schemas.datacontract.org/2004/07/CourseMatesWS.DAL.Objects")]
    [System.SerializableAttribute()]
    public partial class FileType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExstentionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IconClassField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Exstention {
            get {
                return this.ExstentionField;
            }
            set {
                if ((object.ReferenceEquals(this.ExstentionField, value) != true)) {
                    this.ExstentionField = value;
                    this.RaisePropertyChanged("Exstention");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IconClass {
            get {
                return this.IconClassField;
            }
            set {
                if ((object.ReferenceEquals(this.IconClassField, value) != true)) {
                    this.IconClassField = value;
                    this.RaisePropertyChanged("IconClass");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FileStructure", Namespace="http://schemas.datacontract.org/2004/07/CourseMatesWS.DAL.Objects")]
    [System.SerializableAttribute()]
    public partial class FileStructure : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CourseMate.Web.CMwcf.FileItem RootFolderField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CourseMate.Web.CMwcf.FileItem RootFolder {
            get {
                return this.RootFolderField;
            }
            set {
                if ((object.ReferenceEquals(this.RootFolderField, value) != true)) {
                    this.RootFolderField = value;
                    this.RaisePropertyChanged("RootFolder");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CMwcf.ICourseMates")]
    public interface ICourseMates {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICourseMates/Login", ReplyAction="http://tempuri.org/ICourseMates/LoginResponse")]
        string Login(out int id, string userName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICourseMates/Register", ReplyAction="http://tempuri.org/ICourseMates/RegisterResponse")]
        CourseMate.Web.CMwcf.SQLStatus Register(out int userId, out string sessionId, CourseMate.Web.CMwcf.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICourseMates/SendRestorePassword", ReplyAction="http://tempuri.org/ICourseMates/SendRestorePasswordResponse")]
        bool SendRestorePassword(string toSend);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICourseMates/CreateNewCourse", ReplyAction="http://tempuri.org/ICourseMates/CreateNewCourseResponse")]
        int CreateNewCourse(string sessionId, int userId, string courseName, string iconCls);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICourseMates/GetCourseByUserId", ReplyAction="http://tempuri.org/ICourseMates/GetCourseByUserIdResponse")]
        CourseMate.Web.CMwcf.Course[] GetCourseByUserId(string sessionId, string userId);
        
        // CODEGEN: Generating message contract since the operation UploadFile is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICourseMates/UploadFile", ReplyAction="http://tempuri.org/ICourseMates/UploadFileResponse")]
        CourseMate.Web.CMwcf.UploadFileResponse UploadFile(CourseMate.Web.CMwcf.UploadFileMsg request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICourseMates/GetCourseFiles", ReplyAction="http://tempuri.org/ICourseMates/GetCourseFilesResponse")]
        CourseMate.Web.CMwcf.FileStructure GetCourseFiles(int courseId);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UploadFileMsg", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UploadFileMsg {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public int CourseId;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public string FileName;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public int ParentId;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public string SessionId;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public int TypeId;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public int UserId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.IO.Stream FileStream;
        
        public UploadFileMsg() {
        }
        
        public UploadFileMsg(int CourseId, string FileName, int ParentId, string SessionId, int TypeId, int UserId, System.IO.Stream FileStream) {
            this.CourseId = CourseId;
            this.FileName = FileName;
            this.ParentId = ParentId;
            this.SessionId = SessionId;
            this.TypeId = TypeId;
            this.UserId = UserId;
            this.FileStream = FileStream;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadFileResponse {
        
        public UploadFileResponse() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICourseMatesChannel : CourseMate.Web.CMwcf.ICourseMates, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CourseMatesClient : System.ServiceModel.ClientBase<CourseMate.Web.CMwcf.ICourseMates>, CourseMate.Web.CMwcf.ICourseMates {
        
        public CourseMatesClient() {
        }
        
        public CourseMatesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CourseMatesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CourseMatesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CourseMatesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Login(out int id, string userName, string password) {
            return base.Channel.Login(out id, userName, password);
        }
        
        public CourseMate.Web.CMwcf.SQLStatus Register(out int userId, out string sessionId, CourseMate.Web.CMwcf.User user) {
            return base.Channel.Register(out userId, out sessionId, user);
        }
        
        public bool SendRestorePassword(string toSend) {
            return base.Channel.SendRestorePassword(toSend);
        }
        
        public int CreateNewCourse(string sessionId, int userId, string courseName, string iconCls) {
            return base.Channel.CreateNewCourse(sessionId, userId, courseName, iconCls);
        }
        
        public CourseMate.Web.CMwcf.Course[] GetCourseByUserId(string sessionId, string userId) {
            return base.Channel.GetCourseByUserId(sessionId, userId);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CourseMate.Web.CMwcf.UploadFileResponse CourseMate.Web.CMwcf.ICourseMates.UploadFile(CourseMate.Web.CMwcf.UploadFileMsg request) {
            return base.Channel.UploadFile(request);
        }
        
        public void UploadFile(int CourseId, string FileName, int ParentId, string SessionId, int TypeId, int UserId, System.IO.Stream FileStream) {
            CourseMate.Web.CMwcf.UploadFileMsg inValue = new CourseMate.Web.CMwcf.UploadFileMsg();
            inValue.CourseId = CourseId;
            inValue.FileName = FileName;
            inValue.ParentId = ParentId;
            inValue.SessionId = SessionId;
            inValue.TypeId = TypeId;
            inValue.UserId = UserId;
            inValue.FileStream = FileStream;
            CourseMate.Web.CMwcf.UploadFileResponse retVal = ((CourseMate.Web.CMwcf.ICourseMates)(this)).UploadFile(inValue);
        }
        
        public CourseMate.Web.CMwcf.FileStructure GetCourseFiles(int courseId) {
            return base.Channel.GetCourseFiles(courseId);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CMwcf.IAndroidRest")]
    public interface IAndroidRest {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAndroidRest/LoginREST", ReplyAction="http://tempuri.org/IAndroidRest/LoginRESTResponse")]
        string LoginREST(out int id, string userName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAndroidRest/GetCourseByUserIdREST", ReplyAction="http://tempuri.org/IAndroidRest/GetCourseByUserIdRESTResponse")]
        CourseMate.Web.CMwcf.Course[] GetCourseByUserIdREST(string sessionId, string userId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAndroidRestChannel : CourseMate.Web.CMwcf.IAndroidRest, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AndroidRestClient : System.ServiceModel.ClientBase<CourseMate.Web.CMwcf.IAndroidRest>, CourseMate.Web.CMwcf.IAndroidRest {
        
        public AndroidRestClient() {
        }
        
        public AndroidRestClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AndroidRestClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AndroidRestClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AndroidRestClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string LoginREST(out int id, string userName, string password) {
            return base.Channel.LoginREST(out id, userName, password);
        }
        
        public CourseMate.Web.CMwcf.Course[] GetCourseByUserIdREST(string sessionId, string userId) {
            return base.Channel.GetCourseByUserIdREST(sessionId, userId);
        }
    }
}
