//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseMate.Web.CMwcf {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CMwcf.ICourseMates")]
    public interface ICourseMates {
        
        // CODEGEN: Parameter 'LoginResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICourseMates/Login", ReplyAction="http://tempuri.org/ICourseMates/LoginResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CourseMate.Web.CMwcf.LoginResponse Login(CourseMate.Web.CMwcf.LoginRequest request);
        
        // CODEGEN: Parameter 'user' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICourseMates/Register", ReplyAction="http://tempuri.org/ICourseMates/RegisterResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CourseMate.Web.CMwcf.RegisterResponse Register(CourseMate.Web.CMwcf.RegisterRequest request);
        
        // CODEGEN: Parameter 'toSend' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICourseMates/SendRestorePassword", ReplyAction="http://tempuri.org/ICourseMates/SendRestorePasswordResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CourseMate.Web.CMwcf.SendRestorePasswordResponse SendRestorePassword(CourseMate.Web.CMwcf.SendRestorePasswordRequest request);
        
        // CODEGEN: Parameter 'sessionId' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICourseMates/CreateNewCourse", ReplyAction="http://tempuri.org/ICourseMates/CreateNewCourseResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CourseMate.Web.CMwcf.CreateNewCourseResponse CreateNewCourse(CourseMate.Web.CMwcf.CreateNewCourseRequest request);
        
        // CODEGEN: Parameter 'GetCoursesByUserIdResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICourseMates/GetCoursesByUserId", ReplyAction="http://tempuri.org/ICourseMates/GetCoursesByUserIdResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CourseMate.Web.CMwcf.GetCoursesByUserIdResponse GetCoursesByUserId(CourseMate.Web.CMwcf.GetCoursesByUserIdRequest request);
        
        // CODEGEN: Generating message contract since the operation UploadFile is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICourseMates/UploadFile", ReplyAction="http://tempuri.org/ICourseMates/UploadFileResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CourseMate.Web.CMwcf.UploadFileResponse UploadFile(CourseMate.Web.CMwcf.UploadFileMsg request);
        
        // CODEGEN: Parameter 'GetCourseFilesResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICourseMates/GetCourseFiles", ReplyAction="http://tempuri.org/ICourseMates/GetCourseFilesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CourseMate.Web.CMwcf.GetCourseFilesResponse GetCourseFiles(CourseMate.Web.CMwcf.GetCourseFilesRequest request);
        
        // CODEGEN: Parameter 'sessionId' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICourseMates/DeleteFile", ReplyAction="http://tempuri.org/ICourseMates/DeleteFileResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CourseMate.Web.CMwcf.DeleteFileResponse DeleteFile(CourseMate.Web.CMwcf.DeleteFileRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (DownloadRequestMsg) of message DownloadRequestMsg does not match the default value (GetFile)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICourseMates/GetFile", ReplyAction="http://tempuri.org/ICourseMates/GetFileResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CourseMate.Web.CMwcf.RemoteFileInfoMsg GetFile(CourseMate.Web.CMwcf.DownloadRequestMsg request);
        
        // CODEGEN: Parameter 'GetCoursePartisipantResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICourseMates/GetCoursePartisipant", ReplyAction="http://tempuri.org/ICourseMates/GetCoursePartisipantResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CourseMate.Web.CMwcf.GetCoursePartisipantResponse GetCoursePartisipant(CourseMate.Web.CMwcf.GetCoursePartisipantRequest request);
        
        // CODEGEN: Parameter 'sessionId' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICourseMates/UpdateCourse", ReplyAction="http://tempuri.org/ICourseMates/UpdateCourseResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CourseMate.Web.CMwcf.UpdateCourseResponse UpdateCourse(CourseMate.Web.CMwcf.UpdateCourseRequest request);
        
        // CODEGEN: Parameter 'sessionId' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICourseMates/SetUserAsCourseAdmin", ReplyAction="http://tempuri.org/ICourseMates/SetUserAsCourseAdminResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CourseMate.Web.CMwcf.SetUserAsCourseAdminResponse SetUserAsCourseAdmin(CourseMate.Web.CMwcf.SetUserAsCourseAdminRequest request);
        
        // CODEGEN: Parameter 'sessionId' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICourseMates/DeleteCourse", ReplyAction="http://tempuri.org/ICourseMates/DeleteCourseResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CourseMate.Web.CMwcf.DeleteCourseResponse DeleteCourse(CourseMate.Web.CMwcf.DeleteCourseRequest request);
        
        // CODEGEN: Parameter 'sessionId' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICourseMates/RemoveUserFromCourse", ReplyAction="http://tempuri.org/ICourseMates/RemoveUserFromCourseResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CourseMate.Web.CMwcf.RemoveUserFromCourseResponse RemoveUserFromCourse(CourseMate.Web.CMwcf.RemoveUserFromCourseRequest request);
        
        // CODEGEN: Parameter 'GetTop15UsersResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICourseMates/GetTop15Users", ReplyAction="http://tempuri.org/ICourseMates/GetTop15UsersResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CourseMate.Web.CMwcf.GetTop15UsersResponse GetTop15Users(CourseMate.Web.CMwcf.GetTop15UsersRequest request);
        
        // CODEGEN: Parameter 'sessionId' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICourseMates/AddUserToCourse", ReplyAction="http://tempuri.org/ICourseMates/AddUserToCourseResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CourseMate.Web.CMwcf.AddUserToCourseResponse AddUserToCourse(CourseMate.Web.CMwcf.AddUserToCourseRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Login", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class LoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string userName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string password;
        
        public LoginRequest() {
        }
        
        public LoginRequest(string userName, string password) {
            this.userName = userName;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoginResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class LoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string LoginResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int id;
        
        public LoginResponse() {
        }
        
        public LoginResponse(string LoginResult, int id) {
            this.LoginResult = LoginResult;
            this.id = id;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/CourseMatesWS.DAL.Objects")]
    public partial class User : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string emailField;
        
        private string firstNameField;
        
        private string gCMIdField;
        
        private int idField;
        
        private bool idFieldSpecified;
        
        private bool isAdminField;
        
        private bool isAdminFieldSpecified;
        
        private string lastNameField;
        
        private string passwordField;
        
        private string userNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("Email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
                this.RaisePropertyChanged("FirstName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string GCMId {
            get {
                return this.gCMIdField;
            }
            set {
                this.gCMIdField = value;
                this.RaisePropertyChanged("GCMId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IDSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
                this.RaisePropertyChanged("IDSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public bool IsAdmin {
            get {
                return this.isAdminField;
            }
            set {
                this.isAdminField = value;
                this.RaisePropertyChanged("IsAdmin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsAdminSpecified {
            get {
                return this.isAdminFieldSpecified;
            }
            set {
                this.isAdminFieldSpecified = value;
                this.RaisePropertyChanged("IsAdminSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
                this.RaisePropertyChanged("LastName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
                this.RaisePropertyChanged("UserName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/CourseMatesWS.DAL.Objects")]
    public partial class FileStructure : object, System.ComponentModel.INotifyPropertyChanged {
        
        private FileItem rootFolderField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public FileItem RootFolder {
            get {
                return this.rootFolderField;
            }
            set {
                this.rootFolderField = value;
                this.RaisePropertyChanged("RootFolder");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/CourseMatesWS.DAL.Objects")]
    public partial class FileItem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string fileNameField;
        
        private int idField;
        
        private bool idFieldSpecified;
        
        private bool isFolderField;
        
        private bool isFolderFieldSpecified;
        
        private System.DateTime lastModifyField;
        
        private bool lastModifyFieldSpecified;
        
        private int ownerIdField;
        
        private bool ownerIdFieldSpecified;
        
        private string ownerNameField;
        
        private int perantIDField;
        
        private bool perantIDFieldSpecified;
        
        private int rateField;
        
        private bool rateFieldSpecified;
        
        private int sizeField;
        
        private bool sizeFieldSpecified;
        
        private FileItem[] subItemsField;
        
        private FileType typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string FileName {
            get {
                return this.fileNameField;
            }
            set {
                this.fileNameField = value;
                this.RaisePropertyChanged("FileName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IDSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
                this.RaisePropertyChanged("IDSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool IsFolder {
            get {
                return this.isFolderField;
            }
            set {
                this.isFolderField = value;
                this.RaisePropertyChanged("IsFolder");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsFolderSpecified {
            get {
                return this.isFolderFieldSpecified;
            }
            set {
                this.isFolderFieldSpecified = value;
                this.RaisePropertyChanged("IsFolderSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime LastModify {
            get {
                return this.lastModifyField;
            }
            set {
                this.lastModifyField = value;
                this.RaisePropertyChanged("LastModify");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LastModifySpecified {
            get {
                return this.lastModifyFieldSpecified;
            }
            set {
                this.lastModifyFieldSpecified = value;
                this.RaisePropertyChanged("LastModifySpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int OwnerId {
            get {
                return this.ownerIdField;
            }
            set {
                this.ownerIdField = value;
                this.RaisePropertyChanged("OwnerId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OwnerIdSpecified {
            get {
                return this.ownerIdFieldSpecified;
            }
            set {
                this.ownerIdFieldSpecified = value;
                this.RaisePropertyChanged("OwnerIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string OwnerName {
            get {
                return this.ownerNameField;
            }
            set {
                this.ownerNameField = value;
                this.RaisePropertyChanged("OwnerName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int PerantID {
            get {
                return this.perantIDField;
            }
            set {
                this.perantIDField = value;
                this.RaisePropertyChanged("PerantID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PerantIDSpecified {
            get {
                return this.perantIDFieldSpecified;
            }
            set {
                this.perantIDFieldSpecified = value;
                this.RaisePropertyChanged("PerantIDSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int Rate {
            get {
                return this.rateField;
            }
            set {
                this.rateField = value;
                this.RaisePropertyChanged("Rate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RateSpecified {
            get {
                return this.rateFieldSpecified;
            }
            set {
                this.rateFieldSpecified = value;
                this.RaisePropertyChanged("RateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int Size {
            get {
                return this.sizeField;
            }
            set {
                this.sizeField = value;
                this.RaisePropertyChanged("Size");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SizeSpecified {
            get {
                return this.sizeFieldSpecified;
            }
            set {
                this.sizeFieldSpecified = value;
                this.RaisePropertyChanged("SizeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=9)]
        public FileItem[] SubItems {
            get {
                return this.subItemsField;
            }
            set {
                this.subItemsField = value;
                this.RaisePropertyChanged("SubItems");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public FileType Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/CourseMatesWS.DAL.Objects")]
    public partial class FileType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descriptionField;
        
        private string extensionField;
        
        private int idField;
        
        private bool idFieldSpecified;
        
        private string imageUrlField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string Extension {
            get {
                return this.extensionField;
            }
            set {
                this.extensionField = value;
                this.RaisePropertyChanged("Extension");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IDSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
                this.RaisePropertyChanged("IDSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string ImageUrl {
            get {
                return this.imageUrlField;
            }
            set {
                this.imageUrlField = value;
                this.RaisePropertyChanged("ImageUrl");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/CourseMatesWS.DAL.Objects")]
    public partial class FourmItem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string contentField;
        
        private int idField;
        
        private bool idFieldSpecified;
        
        private User ownerField;
        
        private int perentIdField;
        
        private bool perentIdFieldSpecified;
        
        private int rateField;
        
        private bool rateFieldSpecified;
        
        private string titleField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string Content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
                this.RaisePropertyChanged("Content");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IDSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
                this.RaisePropertyChanged("IDSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public User Owner {
            get {
                return this.ownerField;
            }
            set {
                this.ownerField = value;
                this.RaisePropertyChanged("Owner");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int PerentId {
            get {
                return this.perentIdField;
            }
            set {
                this.perentIdField = value;
                this.RaisePropertyChanged("PerentId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PerentIdSpecified {
            get {
                return this.perentIdFieldSpecified;
            }
            set {
                this.perentIdFieldSpecified = value;
                this.RaisePropertyChanged("PerentIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int Rate {
            get {
                return this.rateField;
            }
            set {
                this.rateField = value;
                this.RaisePropertyChanged("Rate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RateSpecified {
            get {
                return this.rateFieldSpecified;
            }
            set {
                this.rateFieldSpecified = value;
                this.RaisePropertyChanged("RateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
                this.RaisePropertyChanged("Title");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/CourseMatesWS.DAL.Objects")]
    public partial class Course : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int courseAdminIDField;
        
        private bool courseAdminIDFieldSpecified;
        
        private string courseNameField;
        
        private FileItem[] filesField;
        
        private FourmItem[] fourmItemsField;
        
        private int idField;
        
        private bool idFieldSpecified;
        
        private string iconClassField;
        
        private bool isAdminField;
        
        private bool isAdminFieldSpecified;
        
        private User[] participantsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int CourseAdminID {
            get {
                return this.courseAdminIDField;
            }
            set {
                this.courseAdminIDField = value;
                this.RaisePropertyChanged("CourseAdminID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CourseAdminIDSpecified {
            get {
                return this.courseAdminIDFieldSpecified;
            }
            set {
                this.courseAdminIDFieldSpecified = value;
                this.RaisePropertyChanged("CourseAdminIDSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string CourseName {
            get {
                return this.courseNameField;
            }
            set {
                this.courseNameField = value;
                this.RaisePropertyChanged("CourseName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=2)]
        public FileItem[] Files {
            get {
                return this.filesField;
            }
            set {
                this.filesField = value;
                this.RaisePropertyChanged("Files");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=3)]
        public FourmItem[] FourmItems {
            get {
                return this.fourmItemsField;
            }
            set {
                this.fourmItemsField = value;
                this.RaisePropertyChanged("FourmItems");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IDSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
                this.RaisePropertyChanged("IDSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string IconClass {
            get {
                return this.iconClassField;
            }
            set {
                this.iconClassField = value;
                this.RaisePropertyChanged("IconClass");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public bool IsAdmin {
            get {
                return this.isAdminField;
            }
            set {
                this.isAdminField = value;
                this.RaisePropertyChanged("IsAdmin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsAdminSpecified {
            get {
                return this.isAdminFieldSpecified;
            }
            set {
                this.isAdminFieldSpecified = value;
                this.RaisePropertyChanged("IsAdminSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=7)]
        public User[] Participants {
            get {
                return this.participantsField;
            }
            set {
                this.participantsField = value;
                this.RaisePropertyChanged("Participants");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/CourseMatesWS.BLL")]
    public enum SQLStatus {
        
        /// <remarks/>
        Succeeded,
        
        /// <remarks/>
        Failed,
        
        /// <remarks/>
        UserExists,
        
        /// <remarks/>
        EmailExists,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Register", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RegisterRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public CourseMate.Web.CMwcf.User user;
        
        public RegisterRequest() {
        }
        
        public RegisterRequest(CourseMate.Web.CMwcf.User user) {
            this.user = user;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RegisterResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RegisterResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public CourseMate.Web.CMwcf.SQLStatus RegisterResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int userId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string sessionId;
        
        public RegisterResponse() {
        }
        
        public RegisterResponse(CourseMate.Web.CMwcf.SQLStatus RegisterResult, int userId, string sessionId) {
            this.RegisterResult = RegisterResult;
            this.userId = userId;
            this.sessionId = sessionId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendRestorePassword", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendRestorePasswordRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string toSend;
        
        public SendRestorePasswordRequest() {
        }
        
        public SendRestorePasswordRequest(string toSend) {
            this.toSend = toSend;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendRestorePasswordResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendRestorePasswordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool SendRestorePasswordResult;
        
        public SendRestorePasswordResponse() {
        }
        
        public SendRestorePasswordResponse(bool SendRestorePasswordResult) {
            this.SendRestorePasswordResult = SendRestorePasswordResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateNewCourse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CreateNewCourseRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string sessionId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int userId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string courseName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string iconCls;
        
        public CreateNewCourseRequest() {
        }
        
        public CreateNewCourseRequest(string sessionId, int userId, string courseName, string iconCls) {
            this.sessionId = sessionId;
            this.userId = userId;
            this.courseName = courseName;
            this.iconCls = iconCls;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateNewCourseResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CreateNewCourseResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int CreateNewCourseResult;
        
        public CreateNewCourseResponse() {
        }
        
        public CreateNewCourseResponse(int CreateNewCourseResult) {
            this.CreateNewCourseResult = CreateNewCourseResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCoursesByUserId", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetCoursesByUserIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string sessionId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string userId;
        
        public GetCoursesByUserIdRequest() {
        }
        
        public GetCoursesByUserIdRequest(string sessionId, string userId) {
            this.sessionId = sessionId;
            this.userId = userId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCoursesByUserIdResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetCoursesByUserIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/CourseMatesWS.DAL.Objects")]
        public CourseMate.Web.CMwcf.Course[] GetCoursesByUserIdResult;
        
        public GetCoursesByUserIdResponse() {
        }
        
        public GetCoursesByUserIdResponse(CourseMate.Web.CMwcf.Course[] GetCoursesByUserIdResult) {
            this.GetCoursesByUserIdResult = GetCoursesByUserIdResult;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/CourseMatesWS.BLL")]
    public enum FileTypeE {
        
        /// <remarks/>
        Unknown,
        
        /// <remarks/>
        Folder,
        
        /// <remarks/>
        DOC,
        
        /// <remarks/>
        DOCX,
        
        /// <remarks/>
        XLS,
        
        /// <remarks/>
        XLSX,
        
        /// <remarks/>
        PPT,
        
        /// <remarks/>
        PPTX,
        
        /// <remarks/>
        PDF,
        
        /// <remarks/>
        JPG,
        
        /// <remarks/>
        PNG,
        
        /// <remarks/>
        GIF,
        
        /// <remarks/>
        BMP,
        
        /// <remarks/>
        TXT,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UploadFileMsg", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UploadFileMsg {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public int CourseId;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string FileName;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public bool IsFolder;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public int ParentId;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SessionId;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public int Size;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public CourseMate.Web.CMwcf.FileTypeE TypeId;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public int UserId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.IO.Stream FileStream;
        
        public UploadFileMsg() {
        }
        
        public UploadFileMsg(int CourseId, string FileName, bool IsFolder, int ParentId, string SessionId, int Size, CourseMate.Web.CMwcf.FileTypeE TypeId, int UserId, System.IO.Stream FileStream) {
            this.CourseId = CourseId;
            this.FileName = FileName;
            this.IsFolder = IsFolder;
            this.ParentId = ParentId;
            this.SessionId = SessionId;
            this.Size = Size;
            this.TypeId = TypeId;
            this.UserId = UserId;
            this.FileStream = FileStream;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadFileResponse {
        
        public UploadFileResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCourseFiles", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetCourseFilesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string sessionId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int userId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int courseId;
        
        public GetCourseFilesRequest() {
        }
        
        public GetCourseFilesRequest(string sessionId, int userId, int courseId) {
            this.sessionId = sessionId;
            this.userId = userId;
            this.courseId = courseId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCourseFilesResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetCourseFilesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public CourseMate.Web.CMwcf.FileStructure GetCourseFilesResult;
        
        public GetCourseFilesResponse() {
        }
        
        public GetCourseFilesResponse(CourseMate.Web.CMwcf.FileStructure GetCourseFilesResult) {
            this.GetCourseFilesResult = GetCourseFilesResult;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/CourseMatesWS.BLL")]
    public enum DeleteStatus {
        
        /// <remarks/>
        Success,
        
        /// <remarks/>
        Failed,
        
        /// <remarks/>
        Authorized,
        
        /// <remarks/>
        FullFolder,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteFile", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DeleteFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string sessionId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int userId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int fileId;
        
        public DeleteFileRequest() {
        }
        
        public DeleteFileRequest(string sessionId, int userId, int fileId) {
            this.sessionId = sessionId;
            this.userId = userId;
            this.fileId = fileId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteFileResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DeleteFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public CourseMate.Web.CMwcf.DeleteStatus DeleteFileResult;
        
        public DeleteFileResponse() {
        }
        
        public DeleteFileResponse(CourseMate.Web.CMwcf.DeleteStatus DeleteFileResult) {
            this.DeleteFileResult = DeleteFileResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DownloadRequestMsg", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DownloadRequestMsg {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public int FileId;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SessionId;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public int UserId;
        
        public DownloadRequestMsg() {
        }
        
        public DownloadRequestMsg(int FileId, string SessionId, int UserId) {
            this.FileId = FileId;
            this.SessionId = SessionId;
            this.UserId = UserId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RemoteFileInfoMsg", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RemoteFileInfoMsg {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string FileName;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public int Size;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.IO.Stream FileStream;
        
        public RemoteFileInfoMsg() {
        }
        
        public RemoteFileInfoMsg(string FileName, int Size, System.IO.Stream FileStream) {
            this.FileName = FileName;
            this.Size = Size;
            this.FileStream = FileStream;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCoursePartisipant", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetCoursePartisipantRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string sessionId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int userId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int courseId;
        
        public GetCoursePartisipantRequest() {
        }
        
        public GetCoursePartisipantRequest(string sessionId, int userId, int courseId) {
            this.sessionId = sessionId;
            this.userId = userId;
            this.courseId = courseId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCoursePartisipantResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetCoursePartisipantResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/CourseMatesWS.DAL.Objects")]
        public CourseMate.Web.CMwcf.User[] GetCoursePartisipantResult;
        
        public GetCoursePartisipantResponse() {
        }
        
        public GetCoursePartisipantResponse(CourseMate.Web.CMwcf.User[] GetCoursePartisipantResult) {
            this.GetCoursePartisipantResult = GetCoursePartisipantResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateCourse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdateCourseRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string sessionId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int userId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int courseId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string courseName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string iconCls;
        
        public UpdateCourseRequest() {
        }
        
        public UpdateCourseRequest(string sessionId, int userId, int courseId, string courseName, string iconCls) {
            this.sessionId = sessionId;
            this.userId = userId;
            this.courseId = courseId;
            this.courseName = courseName;
            this.iconCls = iconCls;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateCourseResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdateCourseResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool UpdateCourseResult;
        
        public UpdateCourseResponse() {
        }
        
        public UpdateCourseResponse(bool UpdateCourseResult) {
            this.UpdateCourseResult = UpdateCourseResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetUserAsCourseAdmin", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SetUserAsCourseAdminRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string sessionId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int userId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int courseId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public int setUserId;
        
        public SetUserAsCourseAdminRequest() {
        }
        
        public SetUserAsCourseAdminRequest(string sessionId, int userId, int courseId, int setUserId) {
            this.sessionId = sessionId;
            this.userId = userId;
            this.courseId = courseId;
            this.setUserId = setUserId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetUserAsCourseAdminResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SetUserAsCourseAdminResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool SetUserAsCourseAdminResult;
        
        public SetUserAsCourseAdminResponse() {
        }
        
        public SetUserAsCourseAdminResponse(bool SetUserAsCourseAdminResult) {
            this.SetUserAsCourseAdminResult = SetUserAsCourseAdminResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteCourse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DeleteCourseRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string sessionId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int userId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int courseId;
        
        public DeleteCourseRequest() {
        }
        
        public DeleteCourseRequest(string sessionId, int userId, int courseId) {
            this.sessionId = sessionId;
            this.userId = userId;
            this.courseId = courseId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteCourseResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DeleteCourseResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool DeleteCourseResult;
        
        public DeleteCourseResponse() {
        }
        
        public DeleteCourseResponse(bool DeleteCourseResult) {
            this.DeleteCourseResult = DeleteCourseResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RemoveUserFromCourse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RemoveUserFromCourseRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string sessionId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int userId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int courseId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public int deleteUserId;
        
        public RemoveUserFromCourseRequest() {
        }
        
        public RemoveUserFromCourseRequest(string sessionId, int userId, int courseId, int deleteUserId) {
            this.sessionId = sessionId;
            this.userId = userId;
            this.courseId = courseId;
            this.deleteUserId = deleteUserId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RemoveUserFromCourseResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RemoveUserFromCourseResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool RemoveUserFromCourseResult;
        
        public RemoveUserFromCourseResponse() {
        }
        
        public RemoveUserFromCourseResponse(bool RemoveUserFromCourseResult) {
            this.RemoveUserFromCourseResult = RemoveUserFromCourseResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTop15Users", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetTop15UsersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string search;
        
        public GetTop15UsersRequest() {
        }
        
        public GetTop15UsersRequest(string search) {
            this.search = search;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTop15UsersResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetTop15UsersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
        public string[] GetTop15UsersResult;
        
        public GetTop15UsersResponse() {
        }
        
        public GetTop15UsersResponse(string[] GetTop15UsersResult) {
            this.GetTop15UsersResult = GetTop15UsersResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddUserToCourse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddUserToCourseRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string sessionId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int userId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int courseId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string userToAdd;
        
        public AddUserToCourseRequest() {
        }
        
        public AddUserToCourseRequest(string sessionId, int userId, int courseId, string userToAdd) {
            this.sessionId = sessionId;
            this.userId = userId;
            this.courseId = courseId;
            this.userToAdd = userToAdd;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddUserToCourseResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddUserToCourseResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool AddUserToCourseResult;
        
        public AddUserToCourseResponse() {
        }
        
        public AddUserToCourseResponse(bool AddUserToCourseResult) {
            this.AddUserToCourseResult = AddUserToCourseResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICourseMatesChannel : CourseMate.Web.CMwcf.ICourseMates, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CourseMatesClient : System.ServiceModel.ClientBase<CourseMate.Web.CMwcf.ICourseMates>, CourseMate.Web.CMwcf.ICourseMates {
        
        public CourseMatesClient() {
        }
        
        public CourseMatesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CourseMatesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CourseMatesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CourseMatesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CourseMate.Web.CMwcf.LoginResponse CourseMate.Web.CMwcf.ICourseMates.Login(CourseMate.Web.CMwcf.LoginRequest request) {
            return base.Channel.Login(request);
        }
        
        public string Login(string userName, string password, out int id) {
            CourseMate.Web.CMwcf.LoginRequest inValue = new CourseMate.Web.CMwcf.LoginRequest();
            inValue.userName = userName;
            inValue.password = password;
            CourseMate.Web.CMwcf.LoginResponse retVal = ((CourseMate.Web.CMwcf.ICourseMates)(this)).Login(inValue);
            id = retVal.id;
            return retVal.LoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CourseMate.Web.CMwcf.RegisterResponse CourseMate.Web.CMwcf.ICourseMates.Register(CourseMate.Web.CMwcf.RegisterRequest request) {
            return base.Channel.Register(request);
        }
        
        public CourseMate.Web.CMwcf.SQLStatus Register(CourseMate.Web.CMwcf.User user, out int userId, out string sessionId) {
            CourseMate.Web.CMwcf.RegisterRequest inValue = new CourseMate.Web.CMwcf.RegisterRequest();
            inValue.user = user;
            CourseMate.Web.CMwcf.RegisterResponse retVal = ((CourseMate.Web.CMwcf.ICourseMates)(this)).Register(inValue);
            userId = retVal.userId;
            sessionId = retVal.sessionId;
            return retVal.RegisterResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CourseMate.Web.CMwcf.SendRestorePasswordResponse CourseMate.Web.CMwcf.ICourseMates.SendRestorePassword(CourseMate.Web.CMwcf.SendRestorePasswordRequest request) {
            return base.Channel.SendRestorePassword(request);
        }
        
        public bool SendRestorePassword(string toSend) {
            CourseMate.Web.CMwcf.SendRestorePasswordRequest inValue = new CourseMate.Web.CMwcf.SendRestorePasswordRequest();
            inValue.toSend = toSend;
            CourseMate.Web.CMwcf.SendRestorePasswordResponse retVal = ((CourseMate.Web.CMwcf.ICourseMates)(this)).SendRestorePassword(inValue);
            return retVal.SendRestorePasswordResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CourseMate.Web.CMwcf.CreateNewCourseResponse CourseMate.Web.CMwcf.ICourseMates.CreateNewCourse(CourseMate.Web.CMwcf.CreateNewCourseRequest request) {
            return base.Channel.CreateNewCourse(request);
        }
        
        public int CreateNewCourse(string sessionId, int userId, string courseName, string iconCls) {
            CourseMate.Web.CMwcf.CreateNewCourseRequest inValue = new CourseMate.Web.CMwcf.CreateNewCourseRequest();
            inValue.sessionId = sessionId;
            inValue.userId = userId;
            inValue.courseName = courseName;
            inValue.iconCls = iconCls;
            CourseMate.Web.CMwcf.CreateNewCourseResponse retVal = ((CourseMate.Web.CMwcf.ICourseMates)(this)).CreateNewCourse(inValue);
            return retVal.CreateNewCourseResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CourseMate.Web.CMwcf.GetCoursesByUserIdResponse CourseMate.Web.CMwcf.ICourseMates.GetCoursesByUserId(CourseMate.Web.CMwcf.GetCoursesByUserIdRequest request) {
            return base.Channel.GetCoursesByUserId(request);
        }
        
        public CourseMate.Web.CMwcf.Course[] GetCoursesByUserId(string sessionId, string userId) {
            CourseMate.Web.CMwcf.GetCoursesByUserIdRequest inValue = new CourseMate.Web.CMwcf.GetCoursesByUserIdRequest();
            inValue.sessionId = sessionId;
            inValue.userId = userId;
            CourseMate.Web.CMwcf.GetCoursesByUserIdResponse retVal = ((CourseMate.Web.CMwcf.ICourseMates)(this)).GetCoursesByUserId(inValue);
            return retVal.GetCoursesByUserIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CourseMate.Web.CMwcf.UploadFileResponse CourseMate.Web.CMwcf.ICourseMates.UploadFile(CourseMate.Web.CMwcf.UploadFileMsg request) {
            return base.Channel.UploadFile(request);
        }
        
        public void UploadFile(int CourseId, string FileName, bool IsFolder, int ParentId, string SessionId, int Size, CourseMate.Web.CMwcf.FileTypeE TypeId, int UserId, System.IO.Stream FileStream) {
            CourseMate.Web.CMwcf.UploadFileMsg inValue = new CourseMate.Web.CMwcf.UploadFileMsg();
            inValue.CourseId = CourseId;
            inValue.FileName = FileName;
            inValue.IsFolder = IsFolder;
            inValue.ParentId = ParentId;
            inValue.SessionId = SessionId;
            inValue.Size = Size;
            inValue.TypeId = TypeId;
            inValue.UserId = UserId;
            inValue.FileStream = FileStream;
            CourseMate.Web.CMwcf.UploadFileResponse retVal = ((CourseMate.Web.CMwcf.ICourseMates)(this)).UploadFile(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CourseMate.Web.CMwcf.GetCourseFilesResponse CourseMate.Web.CMwcf.ICourseMates.GetCourseFiles(CourseMate.Web.CMwcf.GetCourseFilesRequest request) {
            return base.Channel.GetCourseFiles(request);
        }
        
        public CourseMate.Web.CMwcf.FileStructure GetCourseFiles(string sessionId, int userId, int courseId) {
            CourseMate.Web.CMwcf.GetCourseFilesRequest inValue = new CourseMate.Web.CMwcf.GetCourseFilesRequest();
            inValue.sessionId = sessionId;
            inValue.userId = userId;
            inValue.courseId = courseId;
            CourseMate.Web.CMwcf.GetCourseFilesResponse retVal = ((CourseMate.Web.CMwcf.ICourseMates)(this)).GetCourseFiles(inValue);
            return retVal.GetCourseFilesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CourseMate.Web.CMwcf.DeleteFileResponse CourseMate.Web.CMwcf.ICourseMates.DeleteFile(CourseMate.Web.CMwcf.DeleteFileRequest request) {
            return base.Channel.DeleteFile(request);
        }
        
        public CourseMate.Web.CMwcf.DeleteStatus DeleteFile(string sessionId, int userId, int fileId) {
            CourseMate.Web.CMwcf.DeleteFileRequest inValue = new CourseMate.Web.CMwcf.DeleteFileRequest();
            inValue.sessionId = sessionId;
            inValue.userId = userId;
            inValue.fileId = fileId;
            CourseMate.Web.CMwcf.DeleteFileResponse retVal = ((CourseMate.Web.CMwcf.ICourseMates)(this)).DeleteFile(inValue);
            return retVal.DeleteFileResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CourseMate.Web.CMwcf.RemoteFileInfoMsg CourseMate.Web.CMwcf.ICourseMates.GetFile(CourseMate.Web.CMwcf.DownloadRequestMsg request) {
            return base.Channel.GetFile(request);
        }
        
        public string GetFile(int FileId, string SessionId, int UserId, out int Size, out System.IO.Stream FileStream) {
            CourseMate.Web.CMwcf.DownloadRequestMsg inValue = new CourseMate.Web.CMwcf.DownloadRequestMsg();
            inValue.FileId = FileId;
            inValue.SessionId = SessionId;
            inValue.UserId = UserId;
            CourseMate.Web.CMwcf.RemoteFileInfoMsg retVal = ((CourseMate.Web.CMwcf.ICourseMates)(this)).GetFile(inValue);
            Size = retVal.Size;
            FileStream = retVal.FileStream;
            return retVal.FileName;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CourseMate.Web.CMwcf.GetCoursePartisipantResponse CourseMate.Web.CMwcf.ICourseMates.GetCoursePartisipant(CourseMate.Web.CMwcf.GetCoursePartisipantRequest request) {
            return base.Channel.GetCoursePartisipant(request);
        }
        
        public CourseMate.Web.CMwcf.User[] GetCoursePartisipant(string sessionId, int userId, int courseId) {
            CourseMate.Web.CMwcf.GetCoursePartisipantRequest inValue = new CourseMate.Web.CMwcf.GetCoursePartisipantRequest();
            inValue.sessionId = sessionId;
            inValue.userId = userId;
            inValue.courseId = courseId;
            CourseMate.Web.CMwcf.GetCoursePartisipantResponse retVal = ((CourseMate.Web.CMwcf.ICourseMates)(this)).GetCoursePartisipant(inValue);
            return retVal.GetCoursePartisipantResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CourseMate.Web.CMwcf.UpdateCourseResponse CourseMate.Web.CMwcf.ICourseMates.UpdateCourse(CourseMate.Web.CMwcf.UpdateCourseRequest request) {
            return base.Channel.UpdateCourse(request);
        }
        
        public bool UpdateCourse(string sessionId, int userId, int courseId, string courseName, string iconCls) {
            CourseMate.Web.CMwcf.UpdateCourseRequest inValue = new CourseMate.Web.CMwcf.UpdateCourseRequest();
            inValue.sessionId = sessionId;
            inValue.userId = userId;
            inValue.courseId = courseId;
            inValue.courseName = courseName;
            inValue.iconCls = iconCls;
            CourseMate.Web.CMwcf.UpdateCourseResponse retVal = ((CourseMate.Web.CMwcf.ICourseMates)(this)).UpdateCourse(inValue);
            return retVal.UpdateCourseResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CourseMate.Web.CMwcf.SetUserAsCourseAdminResponse CourseMate.Web.CMwcf.ICourseMates.SetUserAsCourseAdmin(CourseMate.Web.CMwcf.SetUserAsCourseAdminRequest request) {
            return base.Channel.SetUserAsCourseAdmin(request);
        }
        
        public bool SetUserAsCourseAdmin(string sessionId, int userId, int courseId, int setUserId) {
            CourseMate.Web.CMwcf.SetUserAsCourseAdminRequest inValue = new CourseMate.Web.CMwcf.SetUserAsCourseAdminRequest();
            inValue.sessionId = sessionId;
            inValue.userId = userId;
            inValue.courseId = courseId;
            inValue.setUserId = setUserId;
            CourseMate.Web.CMwcf.SetUserAsCourseAdminResponse retVal = ((CourseMate.Web.CMwcf.ICourseMates)(this)).SetUserAsCourseAdmin(inValue);
            return retVal.SetUserAsCourseAdminResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CourseMate.Web.CMwcf.DeleteCourseResponse CourseMate.Web.CMwcf.ICourseMates.DeleteCourse(CourseMate.Web.CMwcf.DeleteCourseRequest request) {
            return base.Channel.DeleteCourse(request);
        }
        
        public bool DeleteCourse(string sessionId, int userId, int courseId) {
            CourseMate.Web.CMwcf.DeleteCourseRequest inValue = new CourseMate.Web.CMwcf.DeleteCourseRequest();
            inValue.sessionId = sessionId;
            inValue.userId = userId;
            inValue.courseId = courseId;
            CourseMate.Web.CMwcf.DeleteCourseResponse retVal = ((CourseMate.Web.CMwcf.ICourseMates)(this)).DeleteCourse(inValue);
            return retVal.DeleteCourseResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CourseMate.Web.CMwcf.RemoveUserFromCourseResponse CourseMate.Web.CMwcf.ICourseMates.RemoveUserFromCourse(CourseMate.Web.CMwcf.RemoveUserFromCourseRequest request) {
            return base.Channel.RemoveUserFromCourse(request);
        }
        
        public bool RemoveUserFromCourse(string sessionId, int userId, int courseId, int deleteUserId) {
            CourseMate.Web.CMwcf.RemoveUserFromCourseRequest inValue = new CourseMate.Web.CMwcf.RemoveUserFromCourseRequest();
            inValue.sessionId = sessionId;
            inValue.userId = userId;
            inValue.courseId = courseId;
            inValue.deleteUserId = deleteUserId;
            CourseMate.Web.CMwcf.RemoveUserFromCourseResponse retVal = ((CourseMate.Web.CMwcf.ICourseMates)(this)).RemoveUserFromCourse(inValue);
            return retVal.RemoveUserFromCourseResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CourseMate.Web.CMwcf.GetTop15UsersResponse CourseMate.Web.CMwcf.ICourseMates.GetTop15Users(CourseMate.Web.CMwcf.GetTop15UsersRequest request) {
            return base.Channel.GetTop15Users(request);
        }
        
        public string[] GetTop15Users(string search) {
            CourseMate.Web.CMwcf.GetTop15UsersRequest inValue = new CourseMate.Web.CMwcf.GetTop15UsersRequest();
            inValue.search = search;
            CourseMate.Web.CMwcf.GetTop15UsersResponse retVal = ((CourseMate.Web.CMwcf.ICourseMates)(this)).GetTop15Users(inValue);
            return retVal.GetTop15UsersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CourseMate.Web.CMwcf.AddUserToCourseResponse CourseMate.Web.CMwcf.ICourseMates.AddUserToCourse(CourseMate.Web.CMwcf.AddUserToCourseRequest request) {
            return base.Channel.AddUserToCourse(request);
        }
        
        public bool AddUserToCourse(string sessionId, int userId, int courseId, string userToAdd) {
            CourseMate.Web.CMwcf.AddUserToCourseRequest inValue = new CourseMate.Web.CMwcf.AddUserToCourseRequest();
            inValue.sessionId = sessionId;
            inValue.userId = userId;
            inValue.courseId = courseId;
            inValue.userToAdd = userToAdd;
            CourseMate.Web.CMwcf.AddUserToCourseResponse retVal = ((CourseMate.Web.CMwcf.ICourseMates)(this)).AddUserToCourse(inValue);
            return retVal.AddUserToCourseResult;
        }
    }
}
