//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFTest.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ICourseMates")]
    public interface ICourseMates {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICourseMates/GetUrl", ReplyAction="http://tempuri.org/ICourseMates/GetUrlResponse")]
        string GetUrl();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICourseMatesChannel : WCFTest.ServiceReference1.ICourseMates, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CourseMatesClient : System.ServiceModel.ClientBase<WCFTest.ServiceReference1.ICourseMates>, WCFTest.ServiceReference1.ICourseMates {
        
        public CourseMatesClient() {
        }
        
        public CourseMatesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CourseMatesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CourseMatesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CourseMatesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetUrl() {
            return base.Channel.GetUrl();
        }
    }
}
